version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "nix"
    commit-message:
      prefix: "chore"
      include: "scope"

