#!/usr/bin/env bash
# Runtime acceptance for phase P6c-ii of extensions/pi-loom/DESIGN.md: `/wf-new`
# dry-runs the directory it just scaffolded and only then commits it.
#
# One leg, in Node, against real git repositories. The shipped wf-new.js is a
# module body, so it is evaluated the way the engine's sandbox evaluates it —
# `new (async function(){}).constructor(<globals>, source)` — with stub globals
# standing in for the host bridges. `stage` writes the three files a real
# scaffold would leave behind, `dryRun` answers yes or throws, and `shell`
# genuinely runs the command in the scenario's repository, because the claim
# under test is about what git ends up containing.
#
# Why no model and no pi. Everything this phase adds happens *after*
# stage("scaffold", ...) returns, and that stage runs an agent; driving the real
# workflow to this point would cost a model. The parts a stub cannot fake are
# already gated elsewhere: `checks.pi-loom-wf-new-workflow` launches this exact
# script in a real loom (so a parse error, a reserved instrumentation identifier
# or a top-level binding that collides with the stage library fails there), and
# `checks.pi-loom-dry-run` proves dryRun itself inside the vm sandbox.
#
# Usage: loom-wf-new-commit.sh <path-to-workflows/wf-new>
# Runs offline with a throwaway HOME; no network, no API key, no model.
set -euo pipefail

workflow_directory="${1:?usage: loom-wf-new-commit.sh <path-to-workflows/wf-new>}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# git reads $HOME/.gitconfig; an unset or unwritable HOME makes it noisy and, on
# some versions, fatal. Each repository still sets its own identity.
export HOME="$work/home"
mkdir -p "$HOME"

cat >"$work/harness.mjs" <<'MJS'
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const workflowDirectory = process.argv[2];
const work = process.argv[3];

const failures = [];
const check = (label, condition, detail) => {
  if (!condition) failures.push(`${label}${detail === undefined ? "" : `: ${detail}`}`);
};

// The script is a module body: top-level await is allowed and the last
// statement returns the artifact. That is exactly an async function body, which
// is how the engine's vm sandbox runs it too.
const source = readFileSync(join(workflowDirectory, "wf-new.js"), "utf8");
const AsyncFunction = (async function () {}).constructor;
const build = new AsyncFunction("args", "phase", "log", "human", "stage", "dryRun", "shell", "prompt", source);

const git = (repo, ...argv) => execFileSync("git", argv, { cwd: repo, encoding: "utf8" });

const runShell = (cwd, command) => {
  try {
    return { exitCode: 0, stdout: execFileSync("bash", ["-c", command], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }), stderr: "" };
  } catch (error) {
    return { exitCode: error.status ?? 1, stdout: error.stdout ?? "", stderr: error.stderr ?? "" };
  }
};

// A repository with work in flight: one tracked file modified but not staged,
// one unrelated file staged. Both must survive the workflow's own commit.
const makeRepo = (name, { initialise = true, ignorePi = false } = {}) => {
  const repo = join(work, name);
  mkdirSync(repo, { recursive: true });
  if (!initialise) return repo;
  git(repo, "init", "-q", "-b", "main");
  git(repo, "config", "user.email", "wf-new@example.invalid");
  git(repo, "config", "user.name", "wf-new check");
  writeFileSync(join(repo, "tracked.txt"), "base\n");
  if (ignorePi) writeFileSync(join(repo, ".gitignore"), ".pi/\n");
  git(repo, "add", "-A");
  git(repo, "commit", "-q", "-m", "base");
  writeFileSync(join(repo, "tracked.txt"), "base\nedited by the user\n");
  writeFileSync(join(repo, "other.txt"), "staged by the user\n");
  git(repo, "add", "--", "other.txt");
  return repo;
};

const NAME = "audit-flake";
const DIRECTORY = `.pi/workflows/${NAME}`;

// Runs the shipped script with stub host bridges. `record.order` is the whole
// point of the ordering assertion: it interleaves the dry run with every shell
// command, so "verified before anything was committed" is a fact about a list.
const drive = async (repo, { dryRunFails = false } = {}) => {
  const record = { order: [], commands: [], dryRunInput: null, asked: [] };
  const stage = async (stageName, input) => {
    record.order.push(`stage:${stageName}`);
    // What a successful scaffold stage leaves behind, and no more: three files
    // on disk plus the artifact describing them.
    const absolute = join(repo, DIRECTORY);
    mkdirSync(absolute, { recursive: true });
    const command = { name: input.name, description: "generated by the check", script: `${input.name}.js` };
    writeFileSync(join(absolute, "command.json"), `${JSON.stringify(command, null, 2)}\n`);
    writeFileSync(join(absolute, `${input.name}.js`), "return { ok: true };\n");
    writeFileSync(join(absolute, "README.md"), `# /${input.name}\n`);
    return {
      summary: "wrote the workflow",
      notes: "none",
      name: input.name,
      directory: DIRECTORY,
      script: `${input.name}.js`,
      files: [`${DIRECTORY}/command.json`, `${DIRECTORY}/${input.name}.js`, `${DIRECTORY}/README.md`],
      command,
    };
  };
  const dryRun = async (input) => {
    record.order.push("dryRun");
    record.dryRunInput = input;
    // The real dryRun rejects with the reason; the workflow may catch it.
    if (dryRunFails) throw new Error(`Dry run: /${NAME} would not load: SyntaxError: Unexpected token`);
    return {
      name: NAME,
      directory: DIRECTORY,
      signature: `/${NAME} <task>`,
      usage: `usage: /${NAME} "<task>"`,
      requiredArgs: ["task"],
      rejectedInvalidArguments: true,
      rejection: "unknown property __loomDryRun",
    };
  };
  const shell = async (command) => {
    record.order.push(`shell:${command}`);
    record.commands.push(command);
    return runShell(repo, command);
  };
  const human = {
    // Always the first choice: project scope, and the single-agent shape. Reading
    // the offered list rather than repeating its text keeps the stub honest if
    // the wording changes.
    ask: async (input) => {
      record.asked.push(input.name);
      return input.choices[0];
    },
  };
  const artifact = await build(
    { task: "audit flake inputs for staleness", name: NAME },
    async () => {},
    async () => {},
    human,
    stage,
    dryRun,
    shell,
    (template) => template,
  );
  return { artifact, record };
};

const thrown = async (fn) => {
  try {
    await fn();
    return null;
  } catch (error) {
    return error.message;
  }
};

// ============================================ 1. verified, then committed
{
  const repo = makeRepo("committed");
  const before = git(repo, "rev-parse", "HEAD").trim();
  const { artifact, record } = await drive(repo);

  check("the naming question was asked despite a declared name", record.asked.join(",") === "scope,shape", record.asked.join(","));
  check("the dry run never ran", record.dryRunInput !== null);
  check("the dry run was not given the scaffolded directory", record.dryRunInput?.directory === DIRECTORY, JSON.stringify(record.dryRunInput));

  const firstShell = record.order.findIndex((entry) => entry.startsWith("shell:"));
  const dryRunAt = record.order.indexOf("dryRun");
  check("nothing was dry-run", dryRunAt !== -1);
  check("git ran before the dry run", firstShell === -1 || dryRunAt < firstShell, record.order.join(" | "));
  check("the first git command was not the repository probe", record.commands[0] === "git rev-parse --show-toplevel", record.commands[0]);
  for (const command of record.commands.filter((entry) => entry.includes("commit") || entry.includes("add"))) {
    check("a git command was not limited to the scaffold's own path", command.endsWith(`-- ${DIRECTORY}`), command);
  }

  const head = git(repo, "rev-parse", "HEAD").trim();
  check("no commit was created", head !== before);
  check("the artifact does not report the commit", artifact.commit?.committed === true, JSON.stringify(artifact.commit));
  check("the artifact reports a different sha than git", artifact.commit?.sha === head, `${artifact.commit?.sha} vs ${head}`);
  check("the commit subject does not name the workflow", git(repo, "log", "-1", "--format=%s").trim() === `wf-new: add /${NAME} workflow`, git(repo, "log", "-1", "--format=%s").trim());

  const committedFiles = git(repo, "show", "--name-only", "--format=", "HEAD").trim().split("\n").filter(Boolean).sort();
  const expectedFiles = [`${DIRECTORY}/README.md`, `${DIRECTORY}/command.json`, `${DIRECTORY}/${NAME}.js`].sort();
  check("the commit does not contain exactly the scaffold", JSON.stringify(committedFiles) === JSON.stringify(expectedFiles), committedFiles.join(", "));

  // The user's own work is untouched: still staged, still dirty, still uncommitted.
  const status = git(repo, "status", "--porcelain").trim().split("\n").filter(Boolean).sort();
  check("the user's staged file was swept into the commit or lost", status.includes("A  other.txt"), status.join(" | "));
  check("the user's unstaged edit was swept into the commit or lost", status.includes(" M tracked.txt"), status.join(" | "));

  check("the artifact does not report what the dry run saw", artifact.registration?.usage === `usage: /${NAME} "<task>"`, JSON.stringify(artifact.registration));
  check("the artifact does not report the interview", artifact.interview?.name === "declared in launch arguments", JSON.stringify(artifact.interview));
}

// ================================ 2. would not register: fail, commit nothing
{
  const repo = makeRepo("refused");
  const before = git(repo, "rev-parse", "HEAD").trim();
  let record = null;
  const message = await thrown(async () => {
    const driven = await drive(repo, { dryRunFails: true });
    record = driven.record;
    return driven.artifact;
  });

  check("a scaffold that would not register was returned as a success", message !== null);
  check("the failure does not name the directory", message?.includes(DIRECTORY), message ?? "");
  check("the failure does not say nothing was committed", message?.includes("nothing was committed"), message ?? "");
  check("the failure drops the dry run's reason", message?.includes("would not load"), message ?? "");
  check("git ran at all after a failed dry run", git(repo, "rev-parse", "HEAD").trim() === before);
  check("the run was left with an unexpected commit", git(repo, "log", "--format=%s", "-3").trim() === "base", git(repo, "log", "--format=%s", "-3").trim());
  // Reported, not reverted: the files stay where their author can fix them.
  for (const file of ["command.json", `${NAME}.js`, "README.md"]) {
    check("a failed dry run deleted the scaffold", existsSync(join(repo, DIRECTORY, file)), file);
  }
  check("the failure path recorded a shell command", record === null || record.commands.length === 0);
}

// ================================================ 3. not a git repository
{
  const plain = makeRepo("no-git", { initialise: false });
  const { artifact } = await drive(plain);
  check("a missing repository failed the run instead of being reported", artifact.commit?.committed === false, JSON.stringify(artifact.commit));
  check("the reason does not explain the missing repository", artifact.commit?.reason.includes("not a git repository"), artifact.commit?.reason);
  check("the scaffold was not written anyway", existsSync(join(plain, DIRECTORY, "command.json")));
  check("the artifact lost its registration record", artifact.registration?.name === NAME);
}

// ============================================== 4. the path is git-ignored
{
  const repo = makeRepo("ignored", { ignorePi: true });
  const before = git(repo, "rev-parse", "HEAD").trim();
  const { artifact } = await drive(repo);
  check("an ignored path was reported as committed", artifact.commit?.committed === false, JSON.stringify(artifact.commit));
  check("the reason does not name git's refusal", artifact.commit?.reason.includes("git add refused"), artifact.commit?.reason);
  check("an ignored path produced a commit anyway", git(repo, "rev-parse", "HEAD").trim() === before);
}

if (failures.length) {
  console.error("wf-new-commit: leg failed");
  for (const failure of failures) console.error(`  - ${failure}`);
  process.exit(1);
}
MJS

node "$work/harness.mjs" "$workflow_directory" "$work"

echo "wf-new-commit: /wf-new dry-runs the directory it scaffolded and only then commits it -- the commit contains exactly the three scaffold files and leaves the user's own staged and unstaged work alone, a scaffold that would not register fails with the reason and runs no git command at all, and a repository that cannot take the commit is reported rather than thrown"
